export const ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin/dashboard', icon: '📊' },
  { section: 'USERS & PLANS' },
  { label: 'Manage Plans', path: '/admin/manage-plans', icon: '💎' },
  { label: 'Manage Users', path: '/admin/manage-users', icon: '👥' },
  { label: 'Orders', path: '/admin/orders', icon: '🛒' },
  { section: 'FRONT-END CONTENT' },
  { label: 'Front Partners', path: '/admin/front-partner', icon: '🤝' },
  { label: 'FAQ', path: '/admin/faq', icon: '❓' },
  { label: 'Manage Pages', path: '/admin/manage-page', icon: '📄' },
  { label: 'Testimonial', path: '/admin/testimonial', icon: '💬' },
  { label: 'Contact Form', path: '/admin/contact-form', icon: '📋' },
  { section: 'DATA & INTEGRATIONS' },
  { label: 'WA Links data', path: '/admin/wa-link', icon: '🔗' },
  { label: 'Payment Gateways', path: '/admin/payment-gateways', icon: '💳' },
  { label: 'Flowbuilder Template', path: '/admin/flow-builder-template', icon: '🔧' },
  { section: 'SETTINGS' },
  { label: 'Theme Settings', path: '/admin/web-theme', icon: '🎨' },
  { label: 'Social Login', path: '/admin/social-login', icon: '🔐' },
  { label: 'Site Settings', path: '/admin/site-settings', icon: '⚙️' },
  { label: 'SMTP', path: '/admin/smtp', icon: '📧' },
  { label: 'Web Translation', path: '/admin/translation', icon: '🌐' },
  { label: 'Update Web', path: '/admin/update-web', icon: '🔄' },
  { section: 'PRO ADDONS' },
  { label: 'QR Plugin Settings', path: '/admin/qr-plugin-settings', icon: '📱' },
  { label: 'Instagram Config', path: '/admin/instagram-config', icon: '📷', badge: 'NEW' },
  { label: 'Web Notification', path: '/admin/web-notification', icon: '🔔', badge: 'NEW' },
  { label: 'Manual Web Push', path: '/admin/send-web-push', icon: '📤' },
  { label: 'WA Embed Login', path: '/admin/embed-config', icon: '🟢' },
  { label: 'Telegram Config', path: '/admin/telegram-config', icon: '✈️' },
]

export const USER_NAV = [
  { label: 'Dashboard', path: '/user/dashboard' },
  { label: 'Inbox', path: '/user/inbox' },
  { label: 'Kanban', path: '/user/kanban' },
  { label: 'Contacts', path: '/user/contacts' },
  { label: 'Campaigns', path: '/user/campaigns' },
  { label: 'Automation Flows', path: '/user/automation-flows' },
  { label: 'ChatBot', path: '/user/chatbot' },
  { label: 'Meta Templates', path: '/user/create-meta-template' },
  { label: 'Integrations', path: '/user/integrations' },
  { label: 'Meta WhatsApp', path: '/user/link-meta-whatsapp' },
  { label: 'Agent Login', path: '/user/agent-login' },
  { label: 'Agent Task', path: '/user/agent-task' },
  { label: 'Click-to-Chat Launcher', path: '/user/chat-widget' },
  { label: 'Lead Pipeline', path: '/user/pipeline' },
  { label: 'AI Providers', path: '/user/ai-providers' },
  { label: 'Knowledge Base', path: '/user/knowledge-base' },
  { label: 'Websites Manager', path: '/user/website-manager' },
  { label: 'Supervisor Dashboard', path: '/user/supervisor-dashboard' },
  { label: 'Billing', path: '/user/billing' },
  { label: 'API & Webhooks', path: '/user/api-dashboard' },
  { label: 'Webhook Logs', path: '/user/webhook-logs' },
  { label: 'Settings', path: '/user/settings' },
]

export const AGENT_NAV = [
  { label: 'Workspace', path: '/agent/dashboard' },
  { label: 'Assigned Chats', path: '/agent/chats' },
]
