export const ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin/dashboard', icon: '📊' },
  { section: 'USERS & PLANS' },
  { label: 'Manage Plans', path: '/admin/manage-plans', icon: '💎' },
  { label: 'Manage Users', path: '/admin/manage-users', icon: '👥' },
  { label: 'Orders', path: '/admin/orders', icon: '🛒' },
  { section: 'FRONT-END CONTENT' },
  { label: 'Front Partners', path: '/admin/front-partner', icon: '🤝' },
  { label: 'FAQ', path: '/admin/faq', icon: '❓' },
  { label: 'Manage Pages', path: '/admin/manage-page', icon: '📄' },
  { label: 'Testimonial', path: '/admin/testimonial', icon: '💬' },
  { label: 'Contact Form', path: '/admin/contact-form', icon: '📋' },
  { section: 'DATA & INTEGRATIONS' },
  { label: 'WA Links data', path: '/admin/wa-link', icon: '🔗' },
  { label: 'Payment Gateways', path: '/admin/payment-gateways', icon: '💳' },
  { label: 'Flowbuilder Template', path: '/admin/flow-builder-template', icon: '🔧' },
  { section: 'SETTINGS' },
  { label: 'Theme Settings', path: '/admin/web-theme', icon: '🎨' },
  { label: 'Social Login', path: '/admin/social-login', icon: '🔐' },
  { label: 'Site Settings', path: '/admin/site-settings', icon: '⚙️' },
  { label: 'SMTP', path: '/admin/smtp', icon: '📧' },
  { label: 'Web Translation', path: '/admin/translation', icon: '🌐' },
  { label: 'Update Web', path: '/admin/update-web', icon: '🔄' },
  { section: 'PRO ADDONS' },
  { label: 'QR Plugin Settings', path: '/admin/qr-plugin-settings', icon: '📱' },
  { label: 'Instagram Config', path: '/admin/instagram-config', icon: '📷', badge: 'NEW' },
  { label: 'Web Notification', path: '/admin/web-notification', icon: '🔔', badge: 'NEW' },
  { label: 'Manual Web Push', path: '/admin/send-web-push', icon: '📤' },
  { label: 'WA Embed Login', path: '/admin/embed-config', icon: '🟢' },
  { label: 'Telegram Config', path: '/admin/telegram-config', icon: '✈️' },
]

export const USER_NAV = [
  { label: 'Dashboard', path: '/user/dashboard' },
  { label: 'Inbox', path: '/user/inbox' },
  { label: 'Kanban', path: '/user/kanban' },
  { label: 'WhatsApp Forms', path: '/user/whatsapp-forms', badge: 'NEW' },
  { section: 'INSTAGRAM' },
  { label: 'Link Instagram', path: '/user/link-instagram', badge: 'NEW' },
  { label: 'Insta DM Bot', path: '/user/insta-dm-bot', badge: 'NEW' },
  { label: 'Insta Comment DM', path: '/user/insta-comment-dm', badge: 'NEW' },
  { section: 'WHATSAPP QR PLUGIN' },
  { label: 'Add WhatsApp by QR', path: '/user/add-whatsapp-qr' },
  { label: 'WhatsApp Warmer', path: '/user/whatsapp-warmer' },
  { label: 'Rest API', path: '/user/rest-api' },
  { section: 'WA META CONNECT' },
  { label: 'Link Meta WhatsApp', path: '/user/link-meta-whatsapp' },
  { section: 'AUTOMATION & BOTS' },
  { label: 'Automation Flows', path: '/user/automation-flows' },
  { label: 'WA Chatbot', path: '/user/chatbot' },
  { section: 'BROADCASTING' },
  { label: 'Create Meta Template', path: '/user/create-meta-template' },
  { label: 'Send Campaign', path: '/user/campaigns' },
  { label: 'Campaign Dashboard', path: '/user/campaign-dashboard' },
  { label: 'Phonebook', path: '/user/contacts' },
  { section: 'AI WHATSAPP CALLING' },
  { label: 'Create Call Flow', path: '/user/create-call-flow' },
  { label: 'WA Call Logs', path: '/user/wa-call-logs' },
  { label: 'Setup WA Calls', path: '/user/setup-wa-calls' },
  { section: 'META REST API' },
  { label: 'Conversational API', path: '/user/api-dashboard' },
  { label: 'Template API', path: '/user/api-dashboard' },
  { label: 'API Dashboard', path: '/user/api-dashboard' },
  { section: 'WEBHOOK AUTOMATION' },
  { label: 'Manage Webhooks', path: '/user/api-dashboard' },
  { label: 'Webhook Automation', path: '/user/api-dashboard' },
  { label: 'Webhook Logs', path: '/user/webhook-logs' },
  { section: 'TELEGRAM PLUGIN' },
  { label: 'Telegram Sessions', path: '/user/telegram-sessions' },
  { section: 'MORE OPTIONS' },
  { label: 'Web Notification', path: '/user/web-notification' },
  { label: 'Agent Login', path: '/user/agent-login' },
  { label: 'Agent Task', path: '/user/agent-task' },
  { label: 'Chat Widget', path: '/user/chat-widget' },
]


export const AGENT_NAV = [
  { label: 'Workspace', path: '/agent/dashboard' },
  { label: 'Assigned Chats', path: '/agent/chats' },
]
